name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout openstack-helm in subdirectory
        uses: actions/checkout@v2
        with:
          path: ./openstack-helm
          fetch-depth: 0

      - name: Checkout osh infra
        uses: actions/checkout@master
        with:
          name: $GITHUB_REPOSITORY_OWNER/openstack-helm-infra
          path: ./openstack-helm-infra

      - name: Configure Git
        run: |
          ls ./
          cd ./openstack-helm
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Only works if charts are in a subdirectory
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: "openstack-helm"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"